# Generated by Django 6.0.2 on 2026-02-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Naissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acte', models.CharField(max_length=20, verbose_name='N. du registre')),
                ('annee_registre', models.IntegerField(verbose_name='Annee du registre')),
                ('date_declaration', models.DateField(verbose_name='Date de la declaration')),
                ('nom_enfant', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms_enfant', models.CharField(max_length=200, verbose_name='Prenoms')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=1, verbose_name='Sexe')),
                ('date_naissance_lettres', models.CharField(max_length=255, verbose_name='Date en toutes lettres')),
                ('heure_naissance', models.CharField(max_length=100, verbose_name='Heure de naissance')),
                ('lieu_naissance', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('nom_pere', models.CharField(max_length=255, verbose_name='Nom et Prenoms du Pere')),
                ('nationalite_pere', models.CharField(default='Ivoirienne', max_length=50, verbose_name='Nationalite du Pere')),
                ('nom_mere', models.CharField(max_length=255, verbose_name='Nom et Prenoms de la Mere')),
                ('nationalite_mere', models.CharField(default='Ivoirienne', max_length=50, verbose_name='Nationalite de la Mere')),
                ('mention_mariage', models.TextField(default='NEANT', verbose_name='Mention Mariage')),
                ('mention_divorce', models.TextField(default='NEANT', verbose_name='Mention Divorce')),
                ('mention_deces', models.TextField(default='NEANT', verbose_name='Mention Deces')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
    ]
