# Generated by Django 6.0.2 on 2026-02-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeNaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acte', models.CharField(max_length=50)),
                ('annee_registre', models.IntegerField()),
                ('date_declaration', models.DateField()),
                ('nom_enfant', models.CharField(max_length=255)),
                ('prenoms_enfant', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('heure_naissance', models.TimeField()),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('nom_pere', models.CharField(max_length=255)),
                ('nationalite_pere', models.CharField(max_length=100)),
                ('nom_mere', models.CharField(max_length=255)),
                ('nationalite_mere', models.CharField(max_length=100)),
                ('mention_mariage', models.TextField(blank=True, default='NÉANT', null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Naissance',
        ),
    ]
