# Generated by Django 6.0.2 on 2026-02-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0002_actenaissance_delete_naissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actenaissance',
            name='mention_mariage',
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='ment_decede_le',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True, verbose_name='Décédé le'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='ment_deces_lieu',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True, verbose_name='Lieu du décès'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='ment_mariage_avec',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True, verbose_name='Avec (Conjoint)'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='ment_mariage_dissous',
            field=models.TextField(blank=True, default='NÉANT', null=True, verbose_name='Mariage dissous (Divorce)'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='ment_mariage_lieu',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True, verbose_name='À (Lieu du mariage)'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='ment_marie_le',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True, verbose_name='Marié le'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='transcription',
            field=models.TextField(blank=True, null=True, verbose_name='Transcription / Jugements'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='annee_registre',
            field=models.IntegerField(verbose_name='Année du registre'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_declaration',
            field=models.DateField(verbose_name='Date de déclaration'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nationalite_pere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='numero_acte',
            field=models.CharField(max_length=50, verbose_name="N° d'acte"),
        ),
    ]
