# Generated by Django 6.0.2 on 2026-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0003_remove_actenaissance_mention_mariage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actenaissance',
            name='numero_acte',
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='numero_acte_complet',
            field=models.CharField(default='0000 du 01/01/2006', max_length=100, verbose_name="N° de l'acte"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='annee_registre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_declaration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_decede_le',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_deces_lieu',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_mariage_avec',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_mariage_dissous',
            field=models.TextField(blank=True, default='NÉANT', null=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_mariage_lieu',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_marie_le',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='transcription',
            field=models.TextField(blank=True, null=True, verbose_name='Transcription'),
        ),
    ]
