# Generated by Django 6.0.2 on 2026-02-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0004_remove_actenaissance_numero_acte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actenaissance',
            name='annee_registre',
            field=models.IntegerField(verbose_name='Année du registre'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_declaration',
            field=models.DateField(verbose_name='Date de déclaration'),
        ),
    ]
