# Generated by Django 6.0.2 on 2026-02-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0005_alter_actenaissance_annee_registre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=255, verbose_name='Département')),
                ('sous_prefecture', models.CharField(max_length=255, verbose_name='Sous-Préfecture')),
                ('nom_centre', models.CharField(max_length=255, verbose_name='Nom du Centre (ex: Centre de Méo)')),
                ('code_centre', models.CharField(max_length=10, verbose_name='Code du Centre')),
            ],
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_decede_le',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True, verbose_name='Décédé le'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_deces_lieu',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True, verbose_name='Lieu du décès'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_mariage_avec',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True, verbose_name='Conjoint'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_mariage_dissous',
            field=models.TextField(blank=True, default='NÉANT', null=True, verbose_name='Mariage dissous'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_mariage_lieu',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True, verbose_name='Lieu du mariage'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_marie_le',
            field=models.CharField(blank=True, default='NÉANT', max_length=255, null=True, verbose_name='Marié le'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='transcription',
            field=models.TextField(blank=True, null=True, verbose_name='Transcription / Jugements'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registre.structure', verbose_name="Circonscription d'origine"),
            preserve_default=False,
        ),
    ]
