# Generated by Django 6.0.2 on 2026-03-03 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0006_structure_alter_actenaissance_ment_decede_le_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actenaissance',
            name='ment_decede_le',
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='ment_deces_lieu',
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='ment_mariage_avec',
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='ment_mariage_lieu',
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='ment_marie_le',
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='nationalite_mere',
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='nationalite_pere',
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='transcription',
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='annee_registre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_declaration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_mariage_dissous',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='numero_acte_complet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registre.structure'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='code_centre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='structure',
            name='departement',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='structure',
            name='nom_centre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='structure',
            name='sous_prefecture',
            field=models.CharField(max_length=255),
        ),
    ]
