# Generated by Django 6.0.2 on 2026-03-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0007_remove_actenaissance_ment_decede_le_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actenaissance',
            name='annee_registre',
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='numero_acte_complet',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='code_centre',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='departement',
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='numero_registre',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='ment_mariage_dissous',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
