# Generated by Django 6.0.2 on 2026-03-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0008_remove_actenaissance_annee_registre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actenaissance',
            name='nationalite_mere',
            field=models.CharField(default='Ivoirienne', max_length=100),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='nationalite_pere',
            field=models.CharField(default='Ivoirienne', max_length=100),
        ),
    ]
