# Generated by Django 6.0.2 on 2026-03-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0009_actenaissance_nationalite_mere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actenaissance',
            name='annee_registre',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='transcription_justice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nationalite_mere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nationalite_pere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
