# Generated by Django 6.0.2 on 2026-03-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0010_actenaissance_annee_registre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actenaissance',
            name='annee_registre',
            field=models.IntegerField(default=2026),
        ),
    ]
