# Generated by Django 6.0.2 on 2026-03-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0011_alter_actenaissance_annee_registre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actenaissance',
            name='ment_mariage_dissous',
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='conjoint_mariage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Avec'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='date_deces',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Décédé le'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='date_mariage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marié le'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='dissolution_mariage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mariage dissous (Date et décision)'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='lieu_deces',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de décès'),
        ),
    ]
