# Generated by Django 6.0.2 on 2026-03-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0012_remove_actenaissance_ment_mariage_dissous_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Structure Administrative', 'verbose_name_plural': 'Structures Administratives'},
        ),
        migrations.AddField(
            model_name='structure',
            name='prefecture',
            field=models.CharField(default='Non précisée', max_length=255, verbose_name='Préfecture'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='annee_registre',
            field=models.IntegerField(default=2026, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_deces',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Décédé(e) le'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_declaration',
            field=models.DateField(verbose_name='Date de déclaration'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_mariage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marié(e) le'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_naissance',
            field=models.DateField(verbose_name='Né(e) le'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='dissolution_mariage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mariage dissous le'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='heure_naissance',
            field=models.TimeField(blank=True, null=True, verbose_name='À (Heure)'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='lieu_naissance',
            field=models.CharField(max_length=255, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nationalite_mere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité Mère'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nationalite_pere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité Père'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nom_enfant',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la Mère'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du Père'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='numero_registre',
            field=models.IntegerField(default=1, verbose_name='N° Acte'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='prenoms_enfant',
            field=models.CharField(max_length=255, verbose_name='Prénoms'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='transcription_justice',
            field=models.TextField(blank=True, null=True, verbose_name='Transcription / Jugement Supplétif'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='nom_centre',
            field=models.CharField(max_length=255, verbose_name='Nom du Centre'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='sous_prefecture',
            field=models.CharField(max_length=255, verbose_name='Sous-Préfecture'),
        ),
    ]
