# Generated by Django 6.0.3 on 2026-03-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0013_alter_structure_options_structure_prefecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actenaissance',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name="Sexe de l'enfant"),
        ),
    ]
