# Generated by Django 6.0.2 on 2026-03-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0014_actenaissance_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificat', models.CharField(max_length=50, unique=True, verbose_name='Numéro de Registre')),
                ('date_etablissement', models.DateField(verbose_name="Date d'établissement")),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=150, verbose_name='Prénoms')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('piece_identite', models.CharField(help_text='Ex: Carte Consulaire N° 12345...', max_length=100, verbose_name="Pièce d'identité (Type et N°)")),
                ('adresse_locale', models.CharField(max_length=200, verbose_name='Adresse / Quartier de résidence')),
            ],
            options={
                'verbose_name': 'Certificat de Résidence',
                'verbose_name_plural': 'Certificats de Résidence',
            },
        ),
    ]
