# Generated by Django 6.0.2 on 2026-03-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0015_certificatresidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatresidence',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='et de (Nom de la mère)'),
        ),
        migrations.AddField(
            model_name='certificatresidence',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fils/Fille de (Nom du père)'),
        ),
        migrations.AddField(
            model_name='certificatresidence',
            name='resident_depuis',
            field=models.CharField(blank=True, help_text='Ex: 2020', max_length=4, null=True, verbose_name='Résident depuis (Année)'),
        ),
        migrations.AlterField(
            model_name='certificatresidence',
            name='adresse_locale',
            field=models.CharField(max_length=200, verbose_name='Adresse / Quartier'),
        ),
        migrations.AlterField(
            model_name='certificatresidence',
            name='piece_identite',
            field=models.CharField(help_text='Ex: CNI (CC) : BF. 38400...', max_length=100, verbose_name="Pièce d'identité (Type et N°)"),
        ),
    ]
