# Generated by Django 6.0.2 on 2026-03-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0016_certificatresidence_nom_mere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='region',
            field=models.CharField(blank=True, help_text='Ex: DU CAVALLY', max_length=100, null=True, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='nom_centre',
            field=models.CharField(max_length=100, verbose_name='Nom du centre'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='prefecture',
            field=models.CharField(max_length=100, verbose_name='Département / Préfecture'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='sous_prefecture',
            field=models.CharField(max_length=100, verbose_name='Sous-Préfecture'),
        ),
    ]
