# Generated by Django 6.0.3 on 2026-05-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0018_certificatcelibat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatNonDeces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificat', models.CharField(help_text='Ex: 2023/______/SP-TLP', max_length=50, verbose_name='Numéro du Certificat')),
                ('date_etablissement', models.DateField(verbose_name="Date d'établissement")),
                ('nom_officier', models.CharField(max_length=150, verbose_name="Nom de l'Officier (Sous-préfet)")),
                ('annee_registre', models.CharField(max_length=4, verbose_name='Année du registre vérifié')),
                ('nom_defunt', models.CharField(max_length=200, verbose_name='Nom et Prénoms du défunt')),
                ('date_lieu_naissance_defunt', models.CharField(help_text='Ex: vers 1930 à Ziombli', max_length=200, verbose_name='Né(e) le/vers et à')),
                ('nom_pere', models.CharField(max_length=150, verbose_name='Fils / Fille de (Père)')),
                ('nom_mere', models.CharField(max_length=150, verbose_name='Et de (Mère)')),
                ('date_deces', models.CharField(help_text='Ex: 1er janvier 1975 ou 2009', max_length=100, verbose_name='Date présumée du décès')),
                ('lieu_deces', models.CharField(help_text='Ex: Ziombli, Sous-Préfecture de Toulépleu', max_length=150, verbose_name='Lieu du décès')),
                ('nom_declarant', models.CharField(max_length=150, verbose_name='Nom du déclarant')),
                ('infos_declarant', models.CharField(help_text='Ex: né(e) le 29/12/1953 à Méo, Planteur à Méo', max_length=255, verbose_name='Infos (Naissance, profession, domicile)')),
                ('nom_temoin1', models.CharField(max_length=150, verbose_name='Nom du 1er témoin')),
                ('infos_temoin1', models.CharField(help_text='Ex: né le 01/01/1954 à Ziombli, planteur à Ziombli', max_length=255, verbose_name='Infos 1er témoin')),
                ('cni_temoin1', models.CharField(blank=True, help_text='Ex: CNI N° C 0099 2173 07 du 23/10/2009 à Toulepleu', max_length=200, null=True, verbose_name="Pièce d'identité 1er témoin")),
                ('nom_temoin2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du 2ème témoin')),
                ('infos_temoin2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Infos 2ème témoin')),
                ('cni_temoin2', models.CharField(blank=True, max_length=200, null=True, verbose_name="Pièce d'identité 2ème témoin")),
            ],
            options={
                'verbose_name': 'Certificat de Non Déclaration de Décès',
                'verbose_name_plural': 'Certificats de Non Déclaration de Décès',
            },
        ),
    ]
