# Generated by Django 6.0.3 on 2026-05-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0020_certificatnondivorce_certificatnonremariage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatNonSeparationCorps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro du Certificat')),
                ('date_etablissement', models.DateField(verbose_name="Date d'établissement")),
                ('nom_officier', models.CharField(max_length=150, verbose_name="Nom de l'Officier (Sous-préfet)")),
                ('annee_registre_naissance', models.CharField(max_length=4, verbose_name='Année du Registre')),
                ('numero_acte_naissance', models.CharField(max_length=50, verbose_name="N° de l'acte de naissance")),
                ('date_acte_naissance', models.CharField(help_text='Ex: 07/01/1985', max_length=100, verbose_name="Date de l'acte de naissance")),
                ('nom_prenoms', models.CharField(max_length=200, verbose_name='Nom et Prénoms')),
                ('date_naissance', models.CharField(help_text='Ex: 01/01/1985 ou Vers 1925', max_length=100, verbose_name='Né(e) le / vers')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('nom_pere', models.CharField(max_length=150, verbose_name='Fils / Fille de (Père)')),
                ('nom_mere', models.CharField(max_length=150, verbose_name='Et de (Mère)')),
                ('nationalite', models.CharField(default='Ivoirienne', max_length=100, verbose_name='Nationalité')),
                ('domicile', models.CharField(max_length=150, verbose_name='Domicile')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
            ],
            options={
                'verbose_name': 'Certificat de Non Séparation de Corps',
                'verbose_name_plural': 'Certificats de Non Séparation de Corps',
            },
        ),
        migrations.CreateModel(
            name='CertificatVie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro du Certificat')),
                ('date_etablissement', models.DateField(verbose_name="Date d'établissement")),
                ('nom_officier', models.CharField(max_length=150, verbose_name="Nom de l'Officier (Sous-préfet)")),
                ('annee_registre_naissance', models.CharField(max_length=4, verbose_name='Année du Registre')),
                ('numero_acte_naissance', models.CharField(max_length=50, verbose_name="N° de l'acte de naissance")),
                ('date_acte_naissance', models.CharField(max_length=100, verbose_name="Date de l'acte de naissance")),
                ('nom_prenoms', models.CharField(max_length=200, verbose_name='Nom et Prénoms')),
                ('date_naissance', models.CharField(help_text='Ex: 31/12/1950 ou Vers 1925', max_length=100, verbose_name='Né(e) le / vers')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('nom_pere', models.CharField(max_length=150, verbose_name='Fils / Fille de (Père)')),
                ('nom_mere', models.CharField(max_length=150, verbose_name='Et de (Mère)')),
                ('nationalite', models.CharField(default='Ivoirienne', max_length=100, verbose_name='Nationalité')),
                ('domicile', models.CharField(max_length=150, verbose_name='Domicile')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
            ],
            options={
                'verbose_name': 'Certificat de Vie',
                'verbose_name_plural': 'Certificats de Vie',
            },
        ),
    ]
