# Generated by Django 6.0.3 on 2026-05-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0021_certificatnonseparationcorps_certificatvie'),
    ]

    operations = [
        migrations.AddField(
            model_name='actenaissance',
            name='date_naissance_mere',
            field=models.CharField(blank=True, help_text='Ex: 25/08/1975 ou Vers 1975', max_length=100, null=True, verbose_name='Date de naissance de la mère'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='date_naissance_pere',
            field=models.CharField(blank=True, help_text='Ex: 12/05/1970 ou Vers 1970', max_length=100, null=True, verbose_name='Date de naissance du père'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='domicile_mere',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Domicile de la mère'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='domicile_pere',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Domicile du père'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='profession_mere',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Profession de la mère'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='profession_pere',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Profession du père'),
        ),
    ]
