# Generated by Django 6.0.3 on 2026-05-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0022_actenaissance_date_naissance_mere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeMariage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registre', models.CharField(max_length=50, verbose_name="N° de l'acte")),
                ('annee_registre', models.CharField(max_length=4, verbose_name='Année du registre')),
                ('date_mariage', models.CharField(help_text='Ex: 19 décembre 1963', max_length=150, verbose_name='Date du mariage')),
                ('date_etablissement', models.DateField(verbose_name="Date d'établissement de l'extrait")),
                ('nom_officier', models.CharField(max_length=150, verbose_name="Nom de l'Officier d'état civil")),
                ('nom_prenoms_epoux', models.CharField(max_length=255, verbose_name="Nom et Prénoms de l'Époux")),
                ('date_naissance_epoux', models.CharField(help_text='Ex: Vers 1920 ou 12/05/1980', max_length=150, verbose_name='Né le / Vers')),
                ('lieu_naissance_epoux', models.CharField(max_length=150, verbose_name='À (Lieu de naissance)')),
                ('nationalite_epoux', models.CharField(default='Ivoirienne', max_length=100, verbose_name="Nationalité de l'époux")),
                ('pere_epoux', models.CharField(max_length=150, verbose_name='Fils de (Père)')),
                ('nationalite_pere_epoux', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité du père')),
                ('mere_epoux', models.CharField(max_length=150, verbose_name='Et de (Mère)')),
                ('nationalite_mere_epoux', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité de la mère')),
                ('domicile_parents_epoux', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domiciliés à (Parents)')),
                ('nom_prenoms_epouse', models.CharField(max_length=255, verbose_name="Nom et Prénoms de l'Épouse")),
                ('date_naissance_epouse', models.CharField(max_length=150, verbose_name='Née le / Vers')),
                ('lieu_naissance_epouse', models.CharField(max_length=150, verbose_name='À (Lieu de naissance)')),
                ('nationalite_epouse', models.CharField(default='Ivoirienne', max_length=100, verbose_name="Nationalité de l'épouse")),
                ('pere_epouse', models.CharField(max_length=150, verbose_name='Fille de (Père)')),
                ('nationalite_pere_epouse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité du père')),
                ('mere_epouse', models.CharField(max_length=150, verbose_name='Et de (Mère)')),
                ('nationalite_mere_epouse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité de la mère')),
                ('domicile_parents_epouse', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domiciliés à (Parents)')),
                ('mentions_marginales', models.TextField(blank=True, null=True, verbose_name='Mentions (Divorce, Décès, etc.)')),
            ],
            options={
                'verbose_name': 'Extrait de Mariage',
                'verbose_name_plural': 'Extraits de Mariage',
            },
        ),
    ]
