# Generated by Django 6.0.3 on 2026-05-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0023_actemariage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actemariage',
            name='date_mariage',
            field=models.DateField(verbose_name='Date du mariage'),
        ),
    ]
