# Generated by Django 6.0.3 on 2026-05-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0024_alter_actemariage_date_mariage'),
    ]

    operations = [
        migrations.AddField(
            model_name='actenaissance',
            name='nom_sous_prefet',
            field=models.CharField(blank=True, help_text='Ex: TRA Bi Bah Albert', max_length=150, null=True, verbose_name='Nom et Prénoms du Sous-préfet'),
        ),
    ]
