# Generated by Django 6.0.3 on 2026-05-19 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0025_actenaissance_nom_sous_prefet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actenaissance',
            options={'verbose_name': 'Acte de Naissance', 'verbose_name_plural': 'Actes de Naissance'},
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='annee_registre',
            field=models.CharField(max_length=4, verbose_name='Année du registre'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='conjoint_mariage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Conjoint(e)'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_deces',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Date de décès'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_declaration',
            field=models.DateField(blank=True, null=True, verbose_name='Date de declaration'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_mariage',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Date de mariage'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_naissance',
            field=models.CharField(blank=True, help_text='Ex: 12/05/2004 ou 2004', max_length=150, null=True, verbose_name='Date de naissance (ou Année)'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_naissance_mere',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Née le/vers (Mère)'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_naissance_pere',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Né le/vers (Père)'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='dissolution_mariage',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Date de dissolution du mariage'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='domicile_mere',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domiciliée à (Mère)'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='domicile_pere',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilié à (Père)'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='heure_naissance',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de naissance'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='lieu_deces',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu de décès'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='lieu_naissance',
            field=models.CharField(max_length=200, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nationalite_mere',
            field=models.CharField(blank=True, default='Ivoirienne', max_length=100, null=True, verbose_name='Nationalité de la mère'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nationalite_pere',
            field=models.CharField(blank=True, default='Ivoirienne', max_length=100, null=True, verbose_name='Nationalité du père'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nom_enfant',
            field=models.CharField(max_length=150, verbose_name="Nom de l'enfant"),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom et prénoms de la mère'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom et prénoms du père'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='numero_registre',
            field=models.CharField(max_length=50, verbose_name="N° de l'acte"),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='prenoms_enfant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Prénoms de l'enfant"),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registre.structure', verbose_name="Structure d'état civil"),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='transcription_justice',
            field=models.TextField(blank=True, null=True, verbose_name='Transcription de décision de justice'),
        ),
    ]
