# Generated by Django 6.0.3 on 2026-06-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0026_alter_actenaissance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actenaissance',
            name='nom_officier_creation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Officier d'état civil (Créateur de l'acte)"),
        ),
    ]
